### ISSUE TITLE
License

### ISSUE THREAD

**Issue by dsrw** [Lecrapouille/gdcef#10]
Thank you very much for taking this over. It looks terrific, and I'm excited to use it.

Have you communicated with the original authors about relicensing the code? Unfortunately it isn't possible to go from GPL -> MIT without the consent of the copyright holder. Would you like me to reach out to see if they're open to the change?

**Comment by Lecrapouille** [comment]
@dsrw No worry you can use it :) like said in the README, probably not well explained because my English is poor, I'm the original author with the help of friend of mine steacktartar and both of us were the only two committers of the original project and we are both agree to have changed the license. When forking, his name no longer appears on the GitHub wall, but his name is still on the AUTHORS file. Rapiphod came after the fork.

And as also said in the README, the CEF license may contaminate your project. So only beware of this.

**Comment by Lecrapouille** [comment]
@dsrw I rephrased the README. Is this more understandable ?

**Comment by dsrw** [comment]
Yep, that looks great. Thanks! I’m really happy this exists.

**Comment by Lecrapouille** [comment]
@dsrw If you have issues or want to improve the code or doc, do not hesitate to open ticket or pull requests.
