### ISSUE TITLE
Windows demo crashing immediately on play

### ISSUE THREAD

**Issue by daniel-sanche** [Lecrapouille/gdcef#11]
Hey, great project!

I tried compiling this for windows and linux. Linux worked great, and I was able to run the sample projects by following the documentation. 

For windows, compilation seems to finish successfully, but when running the sample project, it exits immediately as soon as I press "run", with no errors printed to the console. I've tried using different versions of godot, and compiling from previous releases, but I'm getting the same result. 

Any ideas what I am missing?

**Comment by Lecrapouille** [comment]
@daniel-sanche Hello ! Sad :( AFAIK I do not have Windows (and from VirtualBox, Godot or my application cannot start since needs Vulkan which is not supported) so I work blindly for this OS. @steacktartar made it work for Windows, but he does not work anymore, and he is busy now. I'll try to ping him. Else @raphipod are you free to help ?

Else to be sure:
- Godot 3.4 or 3.5 (I never tried with Godot 4).
- I use aliases to refer to the `build/` folder. Windows does not like them (need to be admin). Check if they are present.
- Are .gdns and .gdnlib are well-defined for Windows (I set .dll but maybe its .lib) ?
- You can launch the application from Godot and without it: by crash you mean Godot also crash ? By 'previous releases' do you mean CEF or Godot ?

**Comment by Lecrapouille** [comment]
@daniel-sanche @raphipod told me `Godot doesn't get the build files from CEF, so you have to put the Godot executable into the build folder for the project to run` if true maybe I made a regression here https://github.com/Lecrapouille/gdcef/blob/8ae2774ac708aa89087ac88079c7276f4cd78b5d/addons/gdcef/gdcef/src/gdcef.cpp#L95 calling https://github.com/Lecrapouille/gdcef/blob/8ae2774ac708aa89087ac88079c7276f4cd78b5d/addons/gdcef/gdcef/src/gdcef.cpp#L76 calling https://github.com/Lecrapouille/gdcef/blob/8ae2774ac708aa89087ac88079c7276f4cd78b5d/addons/gdcef/gdcef/src/helper.cpp#L84

**Comment by raphipod** [comment]
Confirmed working with commit 2fca3a0 on my end. No need to put the Godot Editor executable in the Build folder anymore now! @daniel-sanche, does it work on your end?

**Comment by daniel-sanche** [comment]
Yeah looks like that worked, thanks!

**Comment by Lecrapouille** [comment]
@daniel-sanche  Ok nice, I fixed it blendy :) Ok so I'll tagged it and send it back to the Godot asset lib
