### ISSUE TITLE
Add Godot smoke test

### ISSUE THREAD

**Issue by daniel-sanche** [Lecrapouille/gdcef#22]
The recent GitHub actions CI are a great start. But it would be helpful if we attempt to run the demo apps using the compiled library, to make sure everything loads correctly. This will help catch regressions going forward

Something like [Gut](https://github.com/bitwes/Gut) could be helpful for this

**Comment by Lecrapouille** [comment]
@daniel-sanche There are GitHub actions rules to export Godot project (here project == demo) to itch.io or to Github I tried it https://saltares.com/continuous-delivery-pipeline-for-godot-and-itch.io/ it worked for basic Godot application but
 I tried without success on the previous project https://github.com/stigmee/install/tree/master/.github/workflows/old I then did not used this github action since we already compiled Godot-editor but AFAIK on Github action there are no export display and I guess it's CEF dies because of this. Even for exporting project Godot needs the export display (probably fixed in Godot4). In addition exportation is only made Linux side. And I tried compiling Godot in server mode or in export mode I just lost my time. So if you wish
