### ISSUE TITLE
Please add support for Godot-4.0

### ISSUE THREAD

**Issue by abetafish** [Lecrapouille/gdcef#30]
I modified MODULE_TARGET = "release" and GODOT_CPP_TARGET = "release" to MODULE_TARGET = "template_release" and GODOT_CPP_TARGET = "template_release" (It won't even work if I don't) ,After that it outputs many errors
![errors](https://user-images.githubusercontent.com/125128628/228822227-92597326-94a8-4dfc-9b85-e5182dffcd76.png)

**Comment by Lecrapouille** [comment]
@abetafish yes, as said Godot 4, is not (yet) supported, with my new job, I've no few time for my personal projects. I guess we have just to add some `#ifdef` in the code but the Godot doc is sometimes very unclear.

In your case you have just a missing lib: maybe `sudo apt-get install libxcb-dri3-dev`

**Comment by Lecrapouille** [comment]
I added a quick and dirty commit and have commented some of my code. As good devs, the Godot devs broke all API but with some `#ifdef` this module can be compatible with Godot 4 and 3. Currently they make me lost compatibility with my hack to display CEF in a texture. I'm not sure to loose time making compatible, but feel free to fix my commit in the https://github.com/Lecrapouille/gdcef/tree/dev-godot-4 branch and push pull request.

**Comment by Lecrapouille** [comment]
@sanath-narasimhan for the moment this plugin is only for Godot 3.4 or 3.5. The patch I made on the dev-godot-4 branch will not work because I commented a lot of code (broken API between Godot 3 and 4) and I do not have time for this project (since the main project using it aborted), but I saw (spied) that @eProgD is trying to implement it https://github.com/eProgD/gdcef  :) Maybe he will give a pull request :)

**Comment by Lecrapouille** [comment]
Thanks to @BlayTheNinth a huge step on making CEF working for Godot 4.2. I have fixed demos 2D and helloCEF, but there is still an issue with keyboard. The demo3D is not compiling due to API change in the script with the initial project https://godotengine.org/asset-library/asset/127 I also cherry picked commits from the master (doc, build script, reshape of the windows ...) @raphipod @daniel-sanche if you are interested in changes. I'll see to swap master and godot-4 branch and create a godot-3.5 branch instead.

**Comment by Lecrapouille** [comment]
I changed branches:
- master is now dummy: the README refers to godot-3 and godot-4 branches.
- godot-3 was the master branch.
- godot-4 was the dev-godot-4 branch.

@BlayTheNinth if I may ask you if you understand why my Windows CI does not work with Godot-4. Have you got these before ? https://github.com/Lecrapouille/gdcef/actions/runs/7496785463/job/20409569013

**Comment by BlayTheNinth** [comment]
I believe that's what the CMakeLists patch was working around. I also ran into those linking errors again when doing a clean build.

For my local build I've since just made the build script rename the `tests` folder inside CEF which will make it skip building those, since all we need from the CEF build is the dll wrapper.

**Comment by Lecrapouille** [comment]
@BlayTheNinth I restored the patch and the CI passed :)

**Comment by Lecrapouille** [comment]
I fixed the keyboard and remade the 3D demos. I'll tag a release and create a ticket for the Godot assets lib
