### ISSUE TITLE
Android Support

### ISSUE THREAD

**Issue by Nitwel** [Lecrapouille/gdcef#46]
How realistic / doable is it, to have this run on android?

**Comment by Lecrapouille** [comment]
@Nitwel for what I know/read, CEF is not available for phone devices. See https://cef-builds.spotifycdn.com/index.html nothing offered. That is strange since chrom* can be built for Android. But building CEF from code source is out of scope of this current project: too long, too complex, too huge to make compile for Godot users (4h of compilation time, ~100 Gb hard drive).

**Comment by Nitwel** [comment]
Thanks for the info!

**Comment by Lecrapouille** [comment]
@Nitwel if you find information. Please share it

**Comment by Cuphead74832** [comment]
> [@Nitwel](https://github.com/Nitwel) for what I know/read, CEF is not available for phone devices. See https://cef-builds.spotifycdn.com/index.html nothing offered. That is strange since chrom* can be built for Android. But building CEF from code source is out of scope of this current project: too long, too complex, too huge to make compile for Godot users (4h of compilation time, ~100 Gb hard drive).

Does this mean It IS not possible to implement in WebGL/HTML exported games?

**Comment by Lecrapouille** [comment]
@Cuphead74832 it's not possible
