### ISSUE TITLE
Missed key inputs

### ISSUE THREAD

**Issue by Lecrapouille** [Lecrapouille/gdcef#55]
for some reason the input is buggy...  your key up / down code looks solid enough on the godot side, yet I find clicks are often missed and in a javascript game the key up doesn't seem to cause the character to stop moving... so maybe there are some other events/input states we need?

https://spatial-audio-demo.livekit.io/

**Comment by salut-c-leo** [comment]
Can confirm it still happens on Godot 4.3 on Windows 11 with v0.12.1 (compiled from git). This is rather annoying because I wanted to implement web games that need arrow keys to navigate around, but only the first input is registered. Maybe something is up in the C++ code for releasing keys? I'm not a C++ programmer so I can't really help on that.

**Comment by Lecrapouille** [comment]
@salut-c-leo I'll remove Godot keyboard ui_map. Conflicting (for ie SPACE key)
